### PR TITLE
Show initial board always

### LINKED ISSUE #17: Add Initial Board to Test Result even when solution passes or fails with runtime error
~~The teacher should be able to decide what to display in each exercise, with possible options: nothing, final board, initial and final board.~~

~~Perhaps initial and final board could be the default.~~

This should work for both passed tests and code with runtime errors.

### PR DESCRIPTION
**Pull request by faloi**
Closes #17

### CODE REVIEW

File: lib/stones-spec/with_gbb_html_rendering.rb [hunk 1]
```diff
@@ -1,15 +1,21 @@
...
-      board_html.read
+      add_caption caption, board_html.read
     ensure
       [identity, board, board_html].compact.each(&:unlink)
     end
+
+    private
+
+    def add_caption(caption, board_html)
+      board_html.sub '<table class="gbs_board">', "<table class=\"gbs_board\">\n<caption>#{caption}</caption>"
```
Comment (flbulgarelli) [inline lib/stones-spec/with_gbb_html_rendering.rb:18]: In order to be consistent with previous changes, I would name it `with_caption` instead of `add_caption`

**Comment by flbulgarelli** [comment]
I like this a lot, but I would also like to have a way of expressing whether I want to show the initial board. Particullary in gobstones initial guides, I need such functionality
